services:
  postgres:
    image: postgres:latest
    container_name: postgres-bsn
    environment:
      POSTGRES_USER: duke
      POSTGRES_PASSWORD: duke
      PGDATA: /data/postgres
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    networks:
      - bsn
    ports:
      - '5432:5432'
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: mail-dev-bsn
    ports:
      - '1025:1025'
      - '1080:1080'

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak-bsn
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      #      KEYCLOAK_ADMIN: admin #deprecated
      #      KEYCLOAK_ADMIN_PASSWORD: admin #deprecated
      KC_HOSTNAME: localhost
      #      KC_HOSTNAME_PORT: 8080
      #      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      #      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: duke
      KC_DB_PASSWORD: duke
    networks:
      - bsn
    ports:
      - '9090:8080'
    command: 'start-dev'
    depends_on:
      - postgres

networks:
  bsn:
    driver: bridge

volumes:
  postgres:
    driver: local
