services:
  postgres:
    image: postgres:latest
    container_name: postgres-bsn
    restart: unless-stopped
    environment:
      POSTGRES_USER: duke
      POSTGRES_PASSWORD: duke
      PGDATA: /data/postgres
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    networks:
      - bsn
    ports:
      - '5432:5432'

  mail-dev:
    image: maildev/maildev
    container_name: mail-dev-bsn
    networks:
      - bsn
    ports:
      - '1025:1025'
      - '1080:1080'

networks:
  bsn:
    driver: bridge

volumes:
  postgres:
    driver: local
