spring:
  application:
    name: inventory
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:hsqldb:mem:testdb2;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
