/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChannelResponse } from '../models/channel-response';
import { createChannel } from '../fn/channel/create-channel';
import { CreateChannel$Params } from '../fn/channel/create-channel';
import { getChannels1 } from '../fn/channel/get-channels-1';
import { GetChannels1$Params } from '../fn/channel/get-channels-1';

@Injectable({ providedIn: 'root' })
export class ChannelService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getChannels1()` */
  static readonly GetChannels1Path = '/channels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChannels1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChannels1$Response(params?: GetChannels1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChannelResponse>>> {
    const obs = getChannels1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChannels1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChannels1(params?: GetChannels1$Params, context?: HttpContext): Observable<Array<ChannelResponse>> {
    const resp = this.getChannels1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ChannelResponse>>): Array<ChannelResponse> => r.body)
    );
  }

  /** Path part for operation `createChannel()` */
  static readonly CreateChannelPath = '/channels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createChannel()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChannel$Response(params: CreateChannel$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = createChannel(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createChannel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChannel(params: CreateChannel$Params, context?: HttpContext): Observable<number> {
    const resp = this.createChannel$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
