/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createMediaMessage } from '../fn/message/create-media-message';
import { CreateMediaMessage$Params } from '../fn/message/create-media-message';
import { createMessage } from '../fn/message/create-message';
import { CreateMessage$Params } from '../fn/message/create-message';
import { getChannels } from '../fn/message/get-channels';
import { GetChannels$Params } from '../fn/message/get-channels';
import { getMessages } from '../fn/message/get-messages';
import { GetMessages$Params } from '../fn/message/get-messages';
import { MessageResponse } from '../models/message-response';

@Injectable({ providedIn: 'root' })
export class MessageService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createMessage()` */
  static readonly CreateMessagePath = '/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMessage$Response(params: CreateMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createMessage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMessage(params: CreateMessage$Params, context?: HttpContext): Observable<void> {
    const resp = this.createMessage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getChannels()` */
  static readonly GetChannelsPath = '/messages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChannels()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChannels$Response(params: GetChannels$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = getChannels(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChannels$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChannels(params: GetChannels$Params, context?: HttpContext): Observable<void> {
    const resp = this.getChannels$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createMediaMessage()` */
  static readonly CreateMediaMessagePath = '/messages/upload-media';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createMediaMessage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createMediaMessage$Response(params: CreateMediaMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createMediaMessage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createMediaMessage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createMediaMessage(params: CreateMediaMessage$Params, context?: HttpContext): Observable<void> {
    const resp = this.createMediaMessage$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getMessages()` */
  static readonly GetMessagesPath = '/messages/channel/{channel-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMessages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessages$Response(params: GetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MessageResponse>>> {
    const obs = getMessages(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMessages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessages(params: GetMessages$Params, context?: HttpContext): Observable<Array<MessageResponse>> {
    const resp = this.getMessages$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<MessageResponse>>): Array<MessageResponse> => r.body)
    );
  }

}
