/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChannelResponse } from '../../models/channel-response';

export interface GetChannels1$Params {
}

export function getChannels1(http: HttpClient, rootUrl: string, params?: GetChannels1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChannelResponse>>> {
  const rb = new RequestBuilder(rootUrl, getChannels1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChannelResponse>>;
    })
  );
}

getChannels1.PATH = '/channels';
