name: book-social-network

services:
  postgres:
    image: postgres:latest
    container_name: postgres-bsn
    restart: unless-stopped
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: book_social_network
    #      POSTGRES_USER: ''
    #      POSTGRES_PASSWORD: ''
    env_file:
      - path: .env.postgres
        required: false
    volumes:
      - postgres:/data/postgres
    networks:
      - bsn
    ports:
      - '5432:5432'

  mail-dev:
    image: maildev/maildev
    container_name: mail-dev-bsn
    profiles: [ 'local' ]
    networks:
      - bsn
    ports:
      - '1025:1025'
      - '1080:1080'

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak-bsn
    restart: unless-stopped
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
    #      KC_BOOTSTRAP_ADMIN_USERNAME: ''
    #      KC_BOOTSTRAP_ADMIN_PASSWORD: ''
    #      KC_DB_USERNAME: ''
    #      KC_DB_PASSWORD: ''
    env_file:
      - path: .env.keycloak
        required: false
    networks:
      - bsn
    ports:
      - '9090:8080'
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    depends_on:
      - postgres

networks:
  bsn:
    driver: bridge

volumes:
  postgres:
    driver: local
