/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChannelResponse {
  id?: number;
  isRecipientOnline?: boolean;
  lastMessageContent?: string;
  lastMessageTime?: string;
  name?: string;
  recipientId?: number;
  senderId?: number;
  unreadCount?: number;
}
