/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExceptionResponse {
  businessErrorCode?: number;
  businessErrorDescription?: string;
  error?: string;
  errors?: {
[key: string]: string;
};
  validationErrors?: Array<string>;
}
