/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackResponse {
  comment?: string;
  id?: number;
  ownFeedback?: boolean;
  score?: number;
}
