/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  content?: string;
  createdAt?: string;
  id?: number;
  media?: Array<string>;
  messageStatus?: 'SENT' | 'DELIVERED' | 'READ';
  messageType?: 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO';
  recipientId?: number;
  senderId?: number;
}
