/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageRequest {
  channelId?: number;
  content?: string;
  messageType?: 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO';
  recipientId?: number;
  senderId?: number;
}
