/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  firstname?: string;
  id?: number;
  isOnline?: boolean;
  lastOnline?: string;
  lastname?: string;
}
