CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE "USERS"
(
    id       BIGINT GENERATED BY DEFAULT AS SEQUENCE USER_SEQ NOT NULL,
    email    VARCHAR(255)                                     NOT NULL,
    password VARCHAR(255)                                     NOT NULL,
    role     VARCHAR(255)                                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "USERS"
    ADD CONSTRAINT uc_user_email UNIQUE (email);
